# Project: Lab_07_assign_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = gps.o coord.o
LINKOBJ  = gps.o coord.o
LIBS     = -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab_07_121_fall_2017.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

gps.o: gps.cpp
	$(CPP) -c gps.cpp -o gps.o $(CXXFLAGS)

coord.o: coord.cpp
	$(CPP) -c coord.cpp -o coord.o $(CXXFLAGS)
