# Project: Lab_08_assign_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = lettercount.o main_lettercount.o
LINKOBJ  = lettercount.o main_lettercount.o
LIBS     = -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab_08_assign_1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

lettercount.o: lettercount.cpp
	$(CPP) -c lettercount.cpp -o lettercount.o $(CXXFLAGS)

main_lettercount.o: main_lettercount.cpp
	$(CPP) -c main_lettercount.cpp -o main_lettercount.o $(CXXFLAGS)
