# Project: Lab_05_121
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Lab_05_exercise_1.o
LINKOBJ  = Lab_05_exercise_1.o
LIBS     = -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/srobe/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab_05_121.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Lab_05_exercise_1.o: Lab_05_exercise_1.cpp
	$(CPP) -c Lab_05_exercise_1.cpp -o Lab_05_exercise_1.o $(CXXFLAGS)
